"""Streamlit UI for DocRouter.

Run:  streamlit run streamlit_app.py
"""
from __future__ import annotations

import streamlit as st

from docrouter.config import CATEGORIES, Config
from docrouter.rag import DocRouterPipeline

st.set_page_config(page_title="DocRouter — Plant Documentation Assistant",
                   page_icon="🏭", layout="wide")

CATEGORY_COLOR = {"safety": "#e74c3c", "maintenance": "#2980b9", "quality": "#27ae60"}

EXAMPLES = [
    "What's the procedure to lock out a machine before servicing it?",
    "How often should we lubricate the pump bearings?",
    "What does Cpk tell us about our process capability?",
    "Do operators need training to drive a forklift?",
    "How do I read an X-bar control chart?",
    "How does sour patch kids taste?",  # out-of-scope demo
]


@st.cache_resource(show_spinner="Loading corpus and building index…")
def get_pipeline() -> DocRouterPipeline:
    return DocRouterPipeline(Config.from_env())


def render_route(ans) -> None:
    cat = ans.route.category
    color = CATEGORY_COLOR.get(cat, "#7f8c8d")
    label = CATEGORIES[cat]["label"]
    st.markdown(
        f"<div style='padding:10px 14px;border-radius:8px;background:{color};"
        f"color:white;display:inline-block;font-weight:600;'>Routed to: {label}</div>",
        unsafe_allow_html=True,
    )
    st.caption(f"Routing method: **{ans.route.method}** · "
               f"confidence **{ans.route.confidence}** · {ans.route.reasoning}")
    if ans.route.scores:
        cols = st.columns(len(ans.route.scores))
        for col, (name, score) in zip(cols, ans.route.scores.items()):
            col.metric(CATEGORIES[name]["label"], f"{score:.0%}")


def main() -> None:
    st.title("🏭 DocRouter")
    st.write("Ask a plant-floor question. It's routed to the right documentation "
             "(Safety, Maintenance, or Quality) and answered with citations.")

    try:
        pipe = get_pipeline()
    except FileNotFoundError:
        st.error("No corpus found. Run `python -m docrouter.ingest` first, then reload.")
        st.stop()

    with st.sidebar:
        st.header("Status")
        if pipe.llm.available:
            st.success(f"LLM routing + synthesis ON\nmodel: `{pipe.cfg.llm_model}`")
        else:
            st.warning("No Portkey key — using lexical fallback "
                       "(BM25 routing + extractive answers).")
        st.caption(f"Retrieval: **{pipe.retrieval_mode}**")
        st.divider()
        st.header("Corpus")
        for cat, stat in pipe.stats.items():
            st.write(f"**{CATEGORIES[cat]['label']}** — "
                     f"{stat['documents']} docs, {stat['chunks']} chunks")
        st.divider()
        st.header("Try an example")
        for ex in EXAMPLES:
            if st.button(ex, use_container_width=True):
                st.session_state["question"] = ex

    question = st.text_input("Your question",
                             value=st.session_state.get("question", ""),
                             placeholder="e.g. What PPE is required for grinding?")
    ask = st.button("Ask", type="primary")

    if ask and question.strip():
        with st.spinner("Routing and retrieving…"):
            ans = pipe.ask(question.strip())

        if not ans.in_scope:
            st.error("Out of scope — not answered")
            st.caption(f"Why: {ans.route.reasoning}")
            st.markdown(ans.answer)
            st.stop()

        render_route(ans)
        st.subheader("Answer")
        st.markdown(ans.answer)
        st.caption(f"Answer generated by: **{ans.answered_by}**")

        st.subheader("Sources")
        if not ans.sources:
            st.info("No matching passages found in the routed category.")
        for s in ans.sources:
            with st.expander(f"[{s['n']}] {s['title']}  ·  relevance {s['score']}"):
                st.write(s["snippet"])
                st.markdown(f"[Open source ↗]({s['url']})")


if __name__ == "__main__":
    main()
